passed compilation on ubuntu 22.04 with some minor changes
openfoamdotcom/openfoam pull request #1
Opened 2024-06-14 10:38 UTC by yinweijie

2024-06-14 10:51 UTC, hsorby requested changes
Thanks for this, can you try out me suggestions and see if it still builds. If it does I think that would match with the rest of the project nicely.

2024-06-14 10:51 UTC, hsorby commented on src/OpenFOAM/CMakeLists.txt
> +find_package(ZLIB REQUIRED)
We have this here: https://github.com/openfoamdotcom/openfoam/blob/d29f00600d42321444580c3d49d167045e01bce4/CMakeLists.txt#L25C1-L25C28

2024-06-14 10:51 UTC, hsorby commented on src/OpenFOAM/CMakeLists.txt
> +endif()
And this https://github.com/openfoamdotcom/openfoam/blob/d29f00600d42321444580c3d49d167045e01bce4/src/OpenFOAM/CMakeLists.txt#L598 should cover these lines.

2024-06-14 10:51 UTC, hsorby commented on src/OpenFOAM/CMakeLists.txt
> +target_link_libraries(OpenFOAM PUBLIC ${ZLIB_LIBRARIES})
We have a target_link_libraries call here: https://github.com/openfoamdotcom/openfoam/blob/d29f00600d42321444580c3d49d167045e01bce4/src/OpenFOAM/CMakeLists.txt#L608

2024-06-14 10:51 UTC, hsorby commented on src/OpenFOAM/CMakeLists.txt
> +target_link_libraries(OpenFOAM PUBLIC ${ZLIB_LIBRARIES})
And we should be able to use `ZLIB::ZLIB` as the link library so that we don't need the target include directories.

2024-06-14 10:52 UTC, hsorby commented
I am wondering how I managed to build without linking to the zlib library??

2024-06-14 13:28 UTC, yinweijie commented
> Thanks for this, can you try out me suggestions and see if it still builds. If it does I think that would match with the rest of the project nicely.

I try to compile on my another desktop ubuntu 22 envrionment and it passed compilation without need to make changes to zlib target link(changes to [thirdparty/CMakeLists.txt "-DCMAKE_POSITION_INDEPENDENT_CODE=ON"](https://github.com/openfoamdotcom/openfoam/pull/1/files#diff-63349b1a36da563bdafd8d31c8f86eb55bc49e0c8daf68d7b817daace0ee09abR84) is still needed). 
Things are little strange. I'll try again on my laptop on Monday.

2024-06-17 08:18 UTC, yinweijie commented
> Thanks for this, can you try out me suggestions and see if it still builds. If it does I think that would match with the rest of the project nicely.

![image](https://github.com/openfoamdotcom/openfoam/assets/23356124/fa98f91b-a372-4aee-9caf-5dca24b76cec)

By testing on my laptop ubuntu 22.04, I still get the error without target link with ZLIB::ZLIB as shown above. So target link to ZLIB::ZLIB is needed.

Here is the final revision I made to your code base:
https://github.com/openfoamdotcom/openfoam/pull/1/files

2024-06-17 08:20 UTC, yinweijie commented
> I am wondering how I managed to build without linking to the zlib library??

That's strange to me also. I can successfully build without target link to ZLIB::ZLIB  on my another laptop ubuntu environment.

2024-08-21 00:02 UTC, hsorby approved these changes

2024-08-21 00:02 UTC, merged